# Generated by Django 3.1.5 on 2021-01-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oreo', '0002_auto_20210119_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='upadted',
            new_name='updated',
        ),
    ]
