# Generated by Django 3.1.5 on 2021-01-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oreo', '0004_auto_20210119_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='write_flag',
            new_name='send_flag',
        ),
    ]
